-- CREATE DATABASE IF NOT EXISTS db_opendoor;

-- USE db_opendoor;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  USER VARCHAR(255) NOT NULL,
  pass VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE sensors (
  id INT PRIMARY KEY AUTO_INCREMENT,
  building VARCHAR(255) NOT NULL,
  door VARCHAR(255) NOT NULL,
  link_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE clients (
  id INT PRIMARY KEY AUTO_INCREMENT,
  id_sensor INT,
  NAME VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  apartment VARCHAR(255) NOT NULL,
  arriving_date DATE NOT NULL,
  expiration_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (id_sensor) REFERENCES sensors(id)
);

CREATE TABLE LOG (
  id INT PRIMARY KEY AUTO_INCREMENT,
  id_client INT,
  ip VARCHAR(255) NOT NULL,
  device VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_client) REFERENCES clients(id)
);
